### ISSUE TITLE
Needs a try/except to catch IndexError

### ISSUE THREAD

**Issue by eur0pa** [RhinoSecurityLabs/SleuthQL#1]
This statement https://github.com/RhinoSecurityLabs/SleuthQL/blob/87ea35b21d25d6a8206e107b7a69a0d2d6552e76/sleuthql.py#L526 needs to be enclosed in a `try / except IndexError` block, or it will raise exceptions under some circumstances (not yet clear why):

```
[+] Loading data from x/sleuthql.xml...
[+] Found 575 requests from proxy history.
[+] Found 540 requests matching x.com hostname.
[+] Found 11 requests matching x.org hostname.
[+] Found 5 requests matching x.net hostname.


[+] Sorting...
Traceback (most recent call last):
  File "sleuthql.py", line 815, in <module>
    main()
  File "sleuthql.py", line 788, in main
    results = createResults(parsed_xml_results)
  File "sleuthql.py", line 704, in createResults
    sqlData = findSQLParams(params)
  File "sleuthql.py", line 628, in findSQLParams
    insertion_point, req = getSQLInsertionPoint(req, loc, key=key)
  File "sleuthql.py", line 526, in getSQLInsertionPoint
    if lines[i][-1] != "*":
IndexError: string index out of range
```

**Comment by djhohnstein** [comment]
As a quick fix, you could try to change L526 to "if lines[i] && lines[i][-1]". I'll take a look at opening up a branch for a more robust solution.

**Comment by eur0pa** [comment]
I fixed it with a super-dirty `try / except IndexError: continue` in my local copy before opening the issue; but I can't find the cause still

**Comment by djhohnstein** [comment]
I created a new branch that I haven't tested yet (will do as I collect more data) but this _should_ print more verbose error messages and fix the issue above. Should also catch more fringe cases where these strings are empty. You can give it a whirl here: https://github.com/RhinoSecurityLabs/SleuthQL/tree/VerboseErrors

**Comment by djhohnstein** [comment]
Fixed for the time being. Will expand upon this as a feature request in the VerboseErrors branch.
